0001 00e6 034770  ERRORLEVEL  008362                                   C/ASM  SHAHE97.EXE
0001 00e7 034770  __QUIT      008390                                   C/ASM  SHAHE97.EXE
0001 0056 034770  __RUN       008b2e                                   C/ASM  SHAHE97.EXE
0001 0157 034770  __QQPUB     00b598                                   C/ASM  SHAHE97.EXE
0001 00e4 034770  PROCNAME    00de18                                   C/ASM  SHAHE97.EXE
0001 00e5 034770  PROCLINE    00de50                                   C/ASM  SHAHE97.EXE
0001 0059 034770  SET         00dfc0                                   C/ASM  SHAHE97.EXE
0001 015b 034770  __MXRELEAS  010002                                   C/ASM  SHAHE97.EXE
0001 00da 034770  ERRORBLOCK  0111f8                                   C/ASM  SHAHE97.EXE
0001 00df 034770  NETERR      01129e                                   C/ASM  SHAHE97.EXE
0001 00e2 034770  ALERT       019bb4                                   C/ASM  SHAHE97.EXE
0001 00e3 034770  OUTERR      01a00a                                   C/ASM  SHAHE97.EXE
0001 0152 034770  NEXTKEY     01bdec                                   C/ASM  SHAHE97.EXE
0001 0086 034770  LASTKEY     01be68                                   C/ASM  SHAHE97.EXE
0001 00ef 034770  SETKEY      01c092                                   C/ASM  SHAHE97.EXE
0001 013c 034770  QQOUT       01c65a                                   C/ASM  SHAHE97.EXE
0001 0151 034770  DISPOUT     01c818                                   C/ASM  SHAHE97.EXE
0001 0076 034770  DEVOUT      01c976                                   C/ASM  SHAHE97.EXE
0001 00f0 034770  __XHELP     01ce18                                   C/ASM  SHAHE97.EXE
0001 0058 034770  DISPBOX     01d006                                   C/ASM  SHAHE97.EXE
0001 0094 034770  MAXROW      01d324                                   C/ASM  SHAHE97.EXE
0001 0095 034770  MAXCOL      01d338                                   C/ASM  SHAHE97.EXE
0001 0015 034770  SETCOLOR    01d94c                                   C/ASM  SHAHE97.EXE
0001 0159 034770  __COLOR     01da74                                   C/ASM  SHAHE97.EXE
0001 0158 034770  SETCURSOR   01da98                                   C/ASM  SHAHE97.EXE
0001 0093 034770  SAVESCREEN  01dab2                                   C/ASM  SHAHE97.EXE
0001 0097 034770  RESTSCREEN  01dc9e                                   C/ASM  SHAHE97.EXE
0001 000f 034770  SCROLL      01de72                                   C/ASM  SHAHE97.EXE
0001 0078 034770  __GET       01f97a                                   C/ASM  SHAHE97.EXE
0001 00f3 034770  __TOGET     02009c                                   C/ASM  SHAHE97.EXE
0001 0049 034770  DBUSEAREA   022568                                   C/ASM  SHAHE97.EXE
0001 0053 034770  DBSKIP      024ba2                                   C/ASM  SHAHE97.EXE
0001 004c 034770  DBGOTO      024c5c                                   C/ASM  SHAHE97.EXE
0001 0048 034770  DBSELECTAR  02548a                                   C/ASM  SHAHE97.EXE
0001 015a 034770  ASCAN       028da2                                   C/ASM  SHAHE97.EXE
0001 005e 034770  ACHOICE     029984                                   C/ASM  SHAHE97.EXE
0001 0001 034770  SHAHE97     03e000   DYN                                    SHAHE97.EXE
0001 0002 034770  MENU1       03e83a   DYN                                    SHAHE97.EXE
0001 0003 034770  MENUPR      03e944   DYN                                    SHAHE97.EXE
0001 0005 034770  MENU2       03e9f8   DYN                                    SHAHE97.EXE
0001 0060 034770  CALEND      03ebc4   DYN                                    SHAHE97.EXE
0001 00f1 034770  __GETCLASS  03ebeb   DYN                                    SHAHE97.EXE
0001 00f8 034770  __GETBLOCK  03ebf6   DYN                                    SHAHE97.EXE
0001 005c 034770  MENU2A      03ec00   DYN                                    SHAHE97.EXE
0001 000a 034770  MENU3       03ecb0   DYN                                    SHAHE97.EXE
0001 000b 034770  MPRINTB     03ee56   DYN                                    SHAHE97.EXE
0001 0126 034770  GETREADER   03ef43   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 014d 034770  __SETFORMA  03efcd   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0120 034770  STATICS$    03efef   DYN   STAT INIT                        SHAHE97.EXE
0001 0062 034770  TABL        03f000   DYN                                    SHAHE97.EXE
0001 0061 034770  HULARM      03f27f   DYN                                    SHAHE97.EXE
0001 0104 034770  __GETSETNA  03f397   DYN                                    SHAHE97.EXE
0001 0105 034770  __GETSETPI  03f3a7   DYN                                    SHAHE97.EXE
0001 0106 034770  __GETSETPB  03f3b7   DYN                                    SHAHE97.EXE
0001 0107 034770  __GETSETPR  03f3c7   DYN                                    SHAHE97.EXE
0001 0108 034770  __GETSETCA  03f3d7   DYN                                    SHAHE97.EXE
0001 010a 034770  __GETSETEX  03f3e7   DYN                                    SHAHE97.EXE
0001 006e 034770  TOMAR       03f400   DYN                                    SHAHE97.EXE
0001 0007 034770  HARC1       03f6ae   DYN                                    SHAHE97.EXE
0001 00d8 034770  __APPINIT   03f7ef   DYN                                    SHAHE97.EXE
0001 007a 034770  SHAPORAC    03f800   DYN                                    SHAHE97.EXE
0001 00ff 034770  __GETBUFFE  03fba9   DYN                                    SHAHE97.EXE
0001 0100 034770  __GETORIGI  03fbbf   DYN                                    SHAHE97.EXE
0001 0101 034770  __GETEXITS  03fbd5   DYN                                    SHAHE97.EXE
0001 0102 034770  __GETREADE  03fbde   DYN                                    SHAHE97.EXE
0001 0103 034770  __GETSETBL  03fbe7   DYN                                    SHAHE97.EXE
0001 0008 034770  ORAC        03fc00   DYN                                    SHAHE97.EXE
0001 00a1 034770  PZ11        03fe26   DYN                                    SHAHE97.EXE
0001 0113 034770  __GETTODEC  03ff56   DYN                                    SHAHE97.EXE
0001 0148 034770  READEXIT    03ffcc   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0150 034770  READINSERT  03ffe3   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0006 034770  TONANV      040000   DYN                                    SHAHE97.EXE
0001 0109 034770  __GETSETBU  040396   DYN                                    SHAHE97.EXE
0001 010b 034770  __GETSETRE  0403b5   DYN                                    SHAHE97.EXE
0001 010f 034770  __GETUNDO   0403c5   DYN                                    SHAHE97.EXE
0001 014f 034770  UPDATED     0403f1   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0092 034770  TONANV2     040400   DYN                                    SHAHE97.EXE
0001 009f 034770  SURB        040c4a   DYN                                    SHAHE97.EXE
0001 00a0 034770  HISNAK      040d26   DYN                                    SHAHE97.EXE
0001 000d 034770  DURAK       040e02   DYN                                    SHAHE97.EXE
0001 0079 034770  READMODAL   040ef5   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0149 034770  GETACTIVE   040fcd   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0156 034770  STATICS$    040fed   DYN   STAT INIT                        SHAHE97.EXE
0001 0004 034770  PROBL1      041000   DYN                                    SHAHE97.EXE
0001 00a2 034770  PZ21        042604   DYN                                    SHAHE97.EXE
0001 00f2 034770  GETNEW      042762   DYN                                    SHAHE97.EXE
0001 00f7 034770  __GETHASFO  0427e3   DYN                                    SHAHE97.EXE
0001 00f9 034770  __GETNAME   0427ee   DYN                                    SHAHE97.EXE
0001 00fa 034770  __GETPICTU  0427f7   DYN                                    SHAHE97.EXE
0001 009d 034770  ZATIK       042800   DYN                                    SHAHE97.EXE
0001 00a3 034770  PZ31        042c5a   DYN                                    SHAHE97.EXE
0001 00a4 034770  PZ41        042d8a   DYN                                    SHAHE97.EXE
0001 009e 034770  ASTVAC      042eb7   DYN                                    SHAHE97.EXE
0001 010c 034770  __GETBADDA  042f93   DYN                                    SHAHE97.EXE
0001 011d 034770  __GETDWLEF  042fdc   DYN                                    SHAHE97.EXE
0001 014e 034770  __KILLREAD  042ff2   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0009 034770  ZATKIORER   043000   DYN                                    SHAHE97.EXE
0001 0128 034770  GETPREVALI  04373b   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0147 034770  READVAR     0437c8   DYN            STATICS$ ref: 155        SHAHE97.EXE
0001 0155 034770  STATICS$    0437ee   DYN   STAT INIT                        SHAHE97.EXE
0001 000c 034770  PRINTB      043800   DYN                                    SHAHE97.EXE
0001 00d9 034770  ERRORSYS    043be6   DYN                                    SHAHE97.EXE
0001 00b8 034770  CORRECT     043c00   DYN                                    SHAHE97.EXE
0001 00e0 034770  ERRORMESSA  043e9e   DYN   STATIC                           SHAHE97.EXE
0001 00ee 034770  __SETHELPK  043fb0   DYN                                    SHAHE97.EXE
0001 00fb 034770  __GETPOSTB  043fd5   DYN                                    SHAHE97.EXE
0001 00fc 034770  __GETPREBL  043fde   DYN                                    SHAHE97.EXE
0001 00fd 034770  __GETCARGO  043fe7   DYN                                    SHAHE97.EXE
0001 00fe 034770  __GETSUBX   043ff0   DYN                                    SHAHE97.EXE
0001 00db 034770  DEFERROR    044000   DYN   STATIC                           SHAHE97.EXE
0001 0130 034770  GETDOSETKE  044243   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0123 034770  SETTLE      0442ac   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 012d 034770  GETAPPLYKE  044400   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 012e 034770  GETPOSTVAL  0446d5   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 0124 034770  POSTACTIVE  0447d0   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 0122 034770  CLEARGETSY  044800   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 0127 034770  RESTOREGET  044890   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 014a 034770  GETREADVAR  0448f1   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 0132 034770  SHOWSCOREB  04495d   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 013f 034770  DATEMSG     0449aa   DYN   STATIC   STATICS$ ref: 120        SHAHE97.EXE
0001 0153 034770  RANGECHECK  044a1d   DYN            STATICS$ ref: 120        SHAHE97.EXE
0001 005a 034770  __ATPROMPT  044b09   DYN            STATICS$ ref: 156        SHAHE97.EXE
0001 005b 034770  __MENUTO    044c00   DYN            STATICS$ ref: 156        SHAHE97.EXE
